name: OWASP

on:
    push:
        branches:
        - main

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with: 
          node-version: '14'
      - name: Install NPM dependencies
        run: |
          npm install
      - uses: sburris/dependency-check-action@master
        with:
          Project-Name: TestApp
      - name: Archive dependency check reports
        uses: actions/upload-artifact@v1
        with:
          name: reports
          path: reports
